### ISSUE TITLE
Repetition of content in Ch 2. 

### ISSUE THREAD

**Issue by Anthlis** [talkpython/getting-started-with-django-course#1]
Hi there, enjoying the course so far, but wanted to let you know that video titled 'Your first django app' is repeated in full at the start of the next video titled 'Apps vs projects' within 'Ch 2. Your First Django App'. It's not a problem as all the content is there, I'm just raising the issue for your awareness. It might be an easy fix by changing a timestamp? Thanks, Anthony

**Comment by mikeckennedy** [comment]
Thank you @Anthlis. I definitely appreciate your letting us know. We take an hour long video and split it into little lessons. Apparently I did that poorly on that one! All fixed now. (cc @cltrudeau)
